version: '2'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - mysql-data:/data
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis-data:/data

  elasticsearch:
    image: elasticsearch:alpine
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/data
      - ./docker/elasticsearch/logging.yml:/usr/share/elasticsearch/config/logging.yml
      - ./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  mailcatcher:
    image: tophfr/mailcatcher
    container_name: mailcatcher
    environment:
      MAIL_HOST: mailcatcher
      MAIL_PORT: 1025
    ports:
      - 1080:1080
      - 1025:1025

  php:
    build:
      context: ./docker/php7-fpm
    image: laravel:php-fpm
    container_name: php
    depends_on:
      - redis
    command: bash -c "sh crontab-install.sh && php-fpm"
    environment:
      REDIS_HOST: 'redis'
      ELASTICSEARCH_HOST: 'elasticsearch'
      MAILCATCHER_HOST: 'mailcatcher'
      MYSQL_HOST: 'mysql'
      DEBUG: 'true'
    volumes:
      - ./app/:/var/www/html:rw

  web:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

volumes:
  redis-data:
    driver: "local"
  elasticsearch-data:
    driver: "local"
  mysql-data:
    driver: "local"